# Generated by Django 4.2.1 on 2023-05-10 18:23

import currency.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('email_from', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='RequestResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('request_method', models.PositiveSmallIntegerField(choices=[(1, 'GET'),
                                                                             (2, 'POST'),
                                                                             (3, 'PUT'),
                                                                             (4, 'PATCH'),
                                                                             (5, 'DELETE'),
                                                                             (6, 'HEAD'),
                                                                             (7, ' OPTIONS')
                                                                             ]
                                                                    )
                 ),
                ('time', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('code', models.SmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=64)),
                ('city', models.CharField(blank=True, max_length=64)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128,
                                                                         null=True,
                                                                         region=None, unique=True)),
                ('logo', models.ImageField(blank=True, null=True,
                                           upload_to=currency.models.source_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('buy', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Buy')),
                ('sell', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Sell')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('currency', models.PositiveSmallIntegerField(choices=[(1, 'Dollar'),
                                                                       (2, 'Euro'),
                                                                       (3, 'Pound Sterling'),
                                                                       (4, 'Yen')
                                                                       ],
                                                              default=1,
                                                              verbose_name='Currency')
                 ),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             to='currency.source')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
