# Generated by Django 4.1.7 on 2023-03-03 17:34

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_alter_source_city_alter_source_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='',
                                                                 max_length=128, null=True,
                                                                 region=None, unique=True),
        ),
    ]
