# Generated by Django 4.1.7 on 2023-03-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_alter_source_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='currency',
            field=models.PositiveSmallIntegerField(choices=[(1, 'USD'), (2, 'EUR'), (3, 'Hryvnia'), (4, 'Pound Sterling'), (5, 'Yen')], default=1),
        ),
    ]
