# Generated by Django 4.1.7 on 2023-04-09 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_alter_rate_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('code_name', models.PositiveSmallIntegerField(
                    choices=[(1, 'Dollar'), (2, 'Euro'), (3, 'Hryvnia'), (4, 'Pound Sterling'),
                             (5, 'Yen')])),
                ('full_name', models.CharField(max_length=64)),
                ('icon_link', models.CharField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='rate',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='currency.currencyinfo'),
        ),
    ]
