# Generated by Django 4.2 on 2023-04-13 19:36

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ('currency', '0007_alter_rate_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='source',
            old_name='source_url',
            new_name='url',
        ),
        migrations.AddField(
            model_name='source',
            name='code',
            field=models.SmallIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rate',
            name='currency',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'Dollar'), (2, 'Euro'), (3, 'Pound Sterling'), (4, 'Yen')], default=1,
                verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='source',
            name='city',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='source',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
