# Generated by Django 4.2 on 2023-05-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('currency', '0009_source_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='name',
        ),
        migrations.AlterField(
            model_name='requestresponselog',
            name='request_method',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'GET'), (2, 'POST'), (3, 'PUT'), (4, 'PATCH'), (5, 'DELETE'),
                         (6, 'HEAD'), (7, ' OPTIONS')]),
        ),
    ]
