version: "3.9"


services:
  backend:
    image: backend_img
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: currency_backend
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - memcached
      - rabbitmq

  celery_common_worker:
    command: celery -A settings worker -l info --autoscale=0,2
    image: backend_img
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: celery_common_worker
    stdin_open: true
    tty: true
    depends_on:
      - postgres
      - memcached
      - rabbitmq

  celery_beat_worker:
    command: celery -A settings worker -Q scheduled_tasks -l info --autoscale=0,3
    image: backend_img
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: celery_beat_worker
    stdin_open: true
    tty: true
    depends_on:
      - postgres
      - memcached
      - rabbitmq

  celery_beat:
    command: celery -A settings beat -l info
    image: backend_img
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: celery_beat
    stdin_open: true
    tty: true
    depends_on:
      - postgres
      - memcached
      - rabbitmq

  memcached:
    image: memcached:1.6.9
    container_name: memcached
    ports:
      - "11211:11211"

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    env_file: ../env/.env
    ports:
      - "5672:5672"
      - "15672:15672"

  # DB deployed in container only for dev purposes
  postgres:
    image: postgres:15.2-alpine
    container_name: postgres
    env_file: ../env/.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - "../nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"

volumes:
  db_data: {}
