name: Lint

on:
  pull_request:

jobs:
  flake8_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Flake8
        run: |
          flake8 --config=./.flake8
          

  pytest_django:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use SECRET_KEY environment variable
        run: |
          printf "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> ./env/.env
          printf "LOCAL_HOSTS=${{ secrets.LOCAL_HOSTS }}" >> ./env/.env
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        working-directory: ./
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        working-directory: ./
        run: pytest ./app/tests --cov=app --cov-report html && coverage report --fail-under=80
